# key-value config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config     ## name of config map
  namespace: default
data:
  database_host: "192.168.0.1"
  debug_mode: "1"
  log_level: "verbose"